// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmpPwa4SG6gFLZlZ2F8bBxC69V-74vT6k',
    appId: '1:201405856975:android:a13d5495fcbbe392828bba',
    messagingSenderId: '201405856975',
    projectId: 'dreamy-9cd07',
    storageBucket: 'dreamy-9cd07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Q2XOcIu3EJyXLT9_oR-bQZGGhZcuC-8',
    appId: '1:201405856975:ios:c3378f7969c962b6828bba',
    messagingSenderId: '201405856975',
    projectId: 'dreamy-9cd07',
    storageBucket: 'dreamy-9cd07.appspot.com',
    iosBundleId: 'com.example.dreamyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4GrOYKEfPcmnqKAAJ5FPIE0gIJ2OmmEA',
    appId: '1:201405856975:web:165ca6aebb5d3b21828bba',
    messagingSenderId: '201405856975',
    projectId: 'dreamy-9cd07',
    authDomain: 'dreamy-9cd07.firebaseapp.com',
    storageBucket: 'dreamy-9cd07.appspot.com',
  );
}
